### ISSUE TITLE
Addon Crashes with Blender 3.4 

### ISSUE THREAD

**Issue by Anemovatis** [Ocupe/Projectors#19]
Getting a crash while adding a new projector with Blender 3.4. Any ideas ?

![Projector_Crashes](https://user-images.githubusercontent.com/57342025/209936685-153abd2b-8ed0-4600-b3ac-f5d06689aa58.png)

**Comment by Ocupe** [comment]
@Anemovatis thank you for reporting this. I'll look into it.

**Comment by Ocupe** [comment]
I can reproduce the problem. It seems that something has changed.
```
Python: Traceback (most recent call last):
  File "/Users/ocupe/Library/Application Support/Blender/3.4/scripts/addons/Projectors-master/projector.py", line 523, in execute
    init_projector(projector.proj_settings, context)
  File "/Users/ocupe/Library/Application Support/Blender/3.4/scripts/addons/Projectors-master/projector.py", line 506, in init_projector
    update_throw_ratio(proj_settings, context)
  File "/Users/ocupe/Library/Application Support/Blender/3.4/scripts/addons/Projectors-master/projector.py", line 275, in update_throw_ratio
    update_projected_texture(proj_settings, context)
  File "/Users/ocupe/Library/Application Support/Blender/3.4/scripts/addons/Projectors-master/projector.py", line 539, in update_projected_texture
    mix_node = group_tree.nodes['Mix.001']
KeyError: 'bpy_prop_collection[key]: key "Mix.001" not found'
```

**Comment by Ocupe** [comment]
@Anemovatis Please download the latest version and try if it fixes the problem. Thanks for reporting it. I don't use Blender that much anymore, so it was important that you reported it. 👍
