### ISSUE TITLE
I meet some problems about use projector

### ISSUE THREAD

**Issue by 1JUNHAO** [Ocupe/Projectors#22]
: Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Projectors-master\projector.py", line 523, in execute
    projector = create_projector(context)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Projectors-master\projector.py", line 477, in create_projector
    add_projector_node_tree_to_spot(spot)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Projectors-master\projector.py", line 231, in add_projector_node_tree_to_spot
    loc = root_tree.nodes['emission'].location
KeyError: 'bpy_prop_collection[key]: key "emission" not found

**Comment by Ocupe** [comment]
Can you elaborate what you did to trigger the error message? Your on Blender version 3.4, right?

**Comment by 1JUNHAO** [comment]
Yeah,right.Now,I have changed to Blender2.8.But I still not very understand how to use this program.I can't project the pattern onto the object.May you can tell me where I can choose the pattern and load into the projector?it will be very thankful to you
