### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by julesmsa13** [Ocupe/Projectors#41]
Hey ! TY for the work, it looks great.
Unfortunaly I got this error when i want to create a projector : 

Python : Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Projectors-main\projector.py", line 555, in execute
    projector = create_projector(context)
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Projectors-main\projector.py", line 505, in create_projector
    add_projector_node_tree_to_spot(spot)
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Projectors-main\projector.py", line 245, in add_projector_node_tree_to_spot
    loc = root_tree.nodes['Emission'].location
KeyError: 'bpy_prop_collection[key]: key "Emission" not found'

Ty for your help

**Comment by Ocupe** [comment]
Did you download the addon from [here](https://github.com/Ocupe/Projectors/releases/tag/v2024.1.1)? 

Your path looks wrong:
> `C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Projectors-main\projector.py`

Should be:
`C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Projectors\projector.py`

Try uninstalling the addon and then downloading and installing the version linked above.

**Comment by julesmsa13** [comment]
Thank you for your response! After following your instructions, here is the error message again:

Python : Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Projectors\projector.py", line 555, in execute
    projector = create_projector(context)
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Projectors\projector.py", line 505, in create_projector
    add_projector_node_tree_to_spot(spot)
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Projectors\projector.py", line 245, in add_projector_node_tree_to_spot
    loc = root_tree.nodes['Emission'].location
KeyError: 'bpy_prop_collection[key]: key "Emission" not found'


It appears that the script is attempting to access a node named "Emission" in root_tree.nodes, but this node does not exist, leading to a KeyError.

**Comment by Ocupe** [comment]
Thanks for checking, I'll look into it when I have time. Just a heads up, this may take some time. PRs are always welcome.

**Comment by julesmsa13** [comment]
Thank you for your response. By changing the language of Blender (switching to English), the issue was resolved. Strange, I didn't think that the interface language would affect the functioning of the addons!

If you have a moment to spare, could you tell me how to change the projected image? I placed my image in the indicated node, but nothing changes.

Thank you in advance.

![failing loading2](https://github.com/Ocupe/Projectors/assets/169791411/7537f4af-6ffd-4b33-8f81-0132340bab7a)

**Comment by Ocupe** [comment]
Hey @julesmsa13, this is unexpected that changing the language has an effect on the addon. I guess the node name should not be used to look up the node. Thanks for investigating.

You never have to touch the node editor to change the image texture. Changing the image is done in the UI here:
<img width="443" alt="image" src="https://github.com/Ocupe/Projectors/assets/11357413/362215be-2d1a-4258-8f85-d02a2401036e">
